#!/usr/bin/env python3
"""Regenerate assets/brand-icons.js, the brand marks used by index.html.

Glyphs are pulled from Lobe Icons (MIT) with one fallback from Simple Icons (CC0),
reduced to their monochrome path data so a single path can be tinted per context:
white on the provider card's logo tile, brand-coloured next to a model id.

    python3 tools/build-brand-icons.py

Add a provider or model family by adding a slug to BRANDS below. `color` is the
brand colour for the logo tile; use None when no confident colour exists and the
card keeps its generated gradient instead.
"""

import re
import sys
import urllib.request
from pathlib import Path

LOBE_VERSION = '1.94.0'
LOBE_URL = f'https://cdn.jsdelivr.net/npm/@lobehub/icons-static-svg@{LOBE_VERSION}/icons/{{slug}}.svg'
SIMPLE_ICONS_URL = 'https://cdn.jsdelivr.net/npm/simple-icons@15/icons/{slug}.svg'

# slug -> brand colour for the logo tile (None keeps the generated gradient)
BRANDS = {
    'openai': '#000000',
    'azure': '#0078D4',
    'azureai': '#0078D4',
    'microsoft': '#0078D4',
    'anthropic': '#D97757',
    'claude': '#D97757',
    'gemini': '#4285F4',
    'gemma': '#4285F4',
    'vertexai': '#4285F4',
    'palm': '#4285F4',
    'deepseek': '#4D6BFE',
    'qwen': '#615CED',
    'kimi': '#16191E',
    'zai': '#3859FF',
    'volcengine': '#1664FF',
    'doubao': '#1664FF',
    'xai': '#000000',
    'mistral': '#FA520F',
    'cohere': '#39594D',
    'perplexity': '#20808D',
    'groq': '#F55036',
    'cerebras': '#F05A28',
    'minimax': '#E73562',
    'bedrock': '#01A88D',
    'aws': '#FF9900',
    'cloudflare': '#F38020',
    'databricks': '#FF3621',
    'fireworks': '#6720FF',
    'together': '#0F6FFF',
    'replicate': '#000000',
    'openrouter': '#64748B',
    'vercel': '#000000',
    'v0': '#000000',
    'githubcopilot': '#24292F',
    'ibm': '#0F62FE',
    'snowflake': '#29B5E8',
    'nvidia': '#76B900',
    'ollama': '#000000',
    'meta': '#0467DF',
    'tencent': '#0052D9',
    'hunyuan': '#0052D9',
    'wenxin': '#2932E1',
    'yi': '#003425',
    'ai21': None,
    'deepinfra': None,
    'sambanova': None,
    'nebius': None,
    'novita': None,
    'lambda': None,
    'anyscale': None,
    'baseten': None,
    'crusoe': None,
    'featherless': None,
    'hyperbolic': None,
    'friendli': None,
    'morph': None,
    'inception': None,
}

# slugs that only Simple Icons carries
SIMPLE_ICONS_SLUGS = {'databricks'}

# the upstream <title> is wrong or awkward for a few of these
NAME_OVERRIDES = {
    'microsoft': 'Microsoft',
    'githubcopilot': 'GitHub Copilot',
    'azureai': 'Azure AI Foundry',
    'vertexai': 'Vertex AI',
    'minimax': 'MiniMax',
    'nvidia': 'NVIDIA',
    'zai': 'Z.AI',
    'wenxin': 'ERNIE',
    'together': 'Together AI',
    'featherless': 'Featherless AI',
    'v0': 'v0',
    'aws': 'Amazon',
    'bedrock': 'Amazon Bedrock',
}

HEADER = '''/*
 * Brand marks for the provider cards and model rows on llmprice.cn.
 *
 * Glyphs are the monochrome path data from Lobe Icons
 * (https://github.com/lobehub/lobe-icons, MIT License, Copyright (c) 2023 LobeHub),
 * except `databricks`, which comes from Simple Icons
 * (https://github.com/simple-icons/simple-icons, CC0 1.0).
 *
 * Every glyph draws with `fill: currentColor` inside a 24x24 viewBox, so one path
 * serves both the white-on-brand logo tile and the small tinted model-row icon.
 * `color` is the brand colour; when it is null the card keeps its generated
 * gradient tile. `name` is the human-readable brand, used for tooltips.
 *
 * Logos belong to their respective owners and are used here only to identify the
 * provider or model family being priced.
 *
 * Generated by tools/build-brand-icons.py - do not hand-edit.
 */
window.BRAND_ICONS = {
'''


def fetch(slug):
    url = (SIMPLE_ICONS_URL if slug in SIMPLE_ICONS_SLUGS else LOBE_URL).format(slug=slug)
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode()


def parse(slug, svg):
    body = svg.strip()
    if not body.startswith('<svg'):
        sys.exit(f'{slug}: not an SVG (got {body[:60]!r})')

    title = re.search(r'<title>(.*?)</title>', body)
    name = NAME_OVERRIDES.get(slug, title.group(1) if title else slug)

    body = re.sub(r'^<svg[^>]*>', '', body)
    body = re.sub(r'</svg>$', '', body)
    body = re.sub(r'<title>.*?</title>', '', body)
    body = re.sub(r'\s+', ' ', body).strip()

    # the page tints one glyph in several contexts, so a baked-in fill would break it
    if 'fill="#' in body:
        sys.exit(f'{slug}: hardcoded fill would ignore the tint')
    # both values land inside single-quoted JS strings
    if "'" in body or "'" in name:
        sys.exit(f'{slug}: single quote would break the emitted JS string')

    return name, body


def main():
    entries = []
    for slug, color in BRANDS.items():
        # index.html derives the tile's second gradient stop from this, and only
        # understands the full #rrggbb form
        if color is not None and not re.fullmatch(r'#[0-9A-Fa-f]{6}', color):
            sys.exit(f'{slug}: colour must be #rrggbb, got {color!r}')
        name, body = parse(slug, fetch(slug))
        rendered_color = f"'{color}'" if color else 'null'
        entries.append(f"    {slug}: {{ name: '{name}', color: {rendered_color}, path: '{body}' }}")

    target = Path(__file__).resolve().parent.parent / 'assets' / 'brand-icons.js'
    target.write_text(HEADER + ',\n'.join(entries) + '\n};\n')
    print(f'wrote {target.relative_to(target.parent.parent)} ({len(BRANDS)} icons)')


if __name__ == '__main__':
    main()
